spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # REDIS (RedisProperties)
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.0.33
    # Redis服务器连接端口
    port: 6380
    # Redis服务器连接密码（默认为空）
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 1000
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 300
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0
    cluster:
      nodes: 192.168.0.31:6379,192.168.0.33:6379,192.168.1.14:6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.0.34:8761/eureka/,http://192.168.0.32:8761/eureka/
